# Generated by Django 5.2.7 on 2025-10-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('opening_price', models.FloatField()),
                ('closing_price', models.FloatField()),
            ],
        ),
    ]
